pipeline {
    agent {
        node { label "AGENT-1" }
    } 

    options{
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm') 
    }
    environment {
        PROJECT = 'roboshop'
        COMPONENT = 'catalogue'
        AWS_REGION = 'us-east-1'
        AWS_ACC_ID = '793770371113'
    }
    stages {
        stage("init") {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                    sh """
                    cd 00-vpc
                    ls -l
                    pwd
                    terraform init
                    """
                }
            }
        }
        stage("plan") {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                    sh """
                    cd 00-vpc
                    ls -l
                    pwd
                    terraform plan
                    """
                }
            }
        }
        stage("apply"){
            parameters {
                string(name: 'Anurag', description: 'Terraform apply by')
                choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'prod'], description: 'Target environment')
            }
            steps{
                if (params.ENVIRONMENT == 'dev'){
                    withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                        sh """
                        cd 00-vpc
                        ls -l
                        """
                    }
                }
                else{
                    echo 'QA and Prod need permission.'
                }
            }
        }
    }
    post {
        always{
            sh "echo 'this will be run always'"
            // cleanWs()
        }
    }
}