pipeline {
    agent {
        node { label "AGENT-1" }
    } 

    options{
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm') 
    }
    environment {
        PROJECT = 'roboshop'
        COMPONENT = '10-sg'
        AWS_REGION = 'us-east-1'
        AWS_ACC_ID = '793770371113'
    }
    parameters {
                string(name: 'APPLIED_BY',defaultValue: 'Anurag', description: 'Terraform apply by')
                choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'prod'], description: 'Target environment')
            }
    stages {
        stage("init") {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                    sh """
                    echo 'env: ${params.ENVIRONMENT}'
                    cd 10-sg
                    ls -l
                    pwd
                    terraform init
                    """
                }
            }
        }
        stage("plan") {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                    sh """
                    cd 10-sg
                    ls -l
                    pwd
                    terraform plan
                    """
                }
            }
        }
        stage("apply"){
            steps{
                script{
                    if (params.ENVIRONMENT == 'dev'){
                        withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                            sh """
                            cd 10-sg
                            ls -l
                            terraform apply -auto-approve
                            """
                        }
                    }
                    else{
                        echo 'QA and Prod need permission.'
                    }
                }
            }
        }
        stage("Triggering Downstreem Job parallelly"){
            parallel{
                stage('triggering 20-bastion'){
                    steps{
                        script{
                            build (
                                job: '20-bastion',
                                wait: false,
                                propagate: false,
                                parameters: [string(name: 'ENVIRONMENT',value: params.ENVIRONMENT), string(name: 'APPLIED_BY',value: env.COMPONENT)]
                            )
                        }   
                    }
                }
                stage('triggering 30-sg-rules'){
                    steps{
                        script{
                            build (
                                job: '30-sg-rules',
                                wait: false,
                                propagate: false,
                                parameters: [string(name: 'ENVIRONMENT',value: params.ENVIRONMENT), string(name: 'APPLIED_BY',value: env.COMPONENT)]
                            )
                        }   
                    }
                }
                stage('triggering 40-ECR'){
                    steps{
                        script{
                            build (
                                job: '40-ECR',
                                wait: false,
                                propagate: false,
                                parameters: [string(name: 'ENVIRONMENT',value: params.ENVIRONMENT), string(name: 'APPLIED_BY',value: env.COMPONENT)]
                            )
                        }   
                    }
                }
                stage('triggering 60-ACM'){
                    steps{
                        script{
                            build (
                                job: '60-ACM',
                                wait: true,
                                propagate: true,
                                parameters: [string(name: 'ENVIRONMENT',value: params.ENVIRONMENT), string(name: 'APPLIED_BY',value: env.COMPONENT)]
                            )
                        }   
                    }
                }
                stage('triggering 80-EKS'){
                    steps{
                        script{
                            build (
                                job: '80-EKS',
                                wait: false,
                                propagate: false,
                                parameters: [string(name: 'ENVIRONMENT',value: params.ENVIRONMENT), string(name: 'APPLIED_BY',value: env.COMPONENT)]
                            )
                        }   
                    }
                }
            }
        }
        stage('triggering 70-ingress-alb'){
            steps{
                script{
                    build (
                        job: '70-ingress-alb',
                        wait: false,
                        propagate: false,
                        parameters: [string(name: 'ENVIRONMENT',value: params.ENVIRONMENT), string(name: 'APPLIED_BY',value: env.COMPONENT)]
                    )
                }   
            }
        }
    }
    post {
        always{
            sh "echo 'this will be run always'"
            // cleanWs()
        }
        success {
            echo "✅ ${env.COMPONENT} created sucess"
            // slackSend / emailext go here (plugins)
        }
    }
}